"""
Django settings for forecast project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import json

if 'DEBUG' not in os.environ:
    import src.env_variable
else:
    pass
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["SECRET_KEY"] 

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = json.loads(os.environ["DEBUG"].lower())  # if false no info error is shown
 
ALLOWED_HOSTS = [os.environ["SERVER_NAME"] , 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'forecast.apps.ForecastConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4',
    'rest_framework',
    'crispy_forms',
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'src.middleware.oauth.OAuthMiddleware',
    'src.middleware.isadmin.IsAdminMiddleware'
]

ROOT_URLCONF = 'src.urls'

# session cookie
SESSION_COOKIE_AGE = 8*60*60 # 8 hours in seconds
SESSION_COOKIE_HTTPONLY=True 
SESSION_COOKIE_SAMESITE='Lax'
SESSION_COOKIE_SAMESITE_FORCE_ALL = True #

# csrf cookie
CSRF_COOKIE_AGE = 8*60*60 # 8 hours in seconds. By default 1 year
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax' #prevents the cookie from being sent in cross-site requests.




TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':[os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static')
]

WSGI_APPLICATION = 'src.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.environ["DB_NAME"],
        'USER': os.environ["DB_USERNAME"],
        'PASSWORD': os.environ["DB_PASSWORD"],
        'HOST': os.environ["DB_HOSTNAME"],
        'PORT': int(os.environ["DB_PORT"]),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Europe/Madrid"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# OAuth Settings
OAUTH_URL_WHITELISTS = []

OAUTH_CLIENT_NAME = 'identityserver4'

OAUTH_CLIENT = {
    'client_id': os.environ["CLIENT_ID"],
    'client_secret': os.environ["CLIENT_SECRET"],
    'server_metadata_url' : os.environ["ID_SERVER_URL"] + '/.well-known/openid-configuration',
    'redirect_uri': os.environ["APP_URL"] + '/signin-oidc',
    'authorization_endpoint':  os.environ["APP_URL"] +'/connect/authorize',
    'client_kwargs': {
        'scope': 'openid profile email cps-forecast-identity',
        'token_endpoint_auth_method': 'client_secret_post',
        'code_challenge_method': 'S256',
        'token_placement': 'header'
    },
    'userinfo_endpoint': os.environ["ID_SERVER_URL"] + '/connect/userinfo',
}

OAUTH_COOKIE_SESSION_ID = 'sso_session_id'



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
        'your_handler': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'debug.log'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django_logger': {
            'handlers': ['your_handler'],
            'level': 'INFO',
            'propagate': True
        }
    },
}

